# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=models.SlugField(default='entry-slug', max_length=100),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='topic-slug', max_length=100),
        ),
    ]
